paths:
  data_path: /home/share/huadjyin/home/zhoutao3/tracks/example_data/11_mouse_Bhattacherjee/process
  input_dir: /home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/01_merfish_pfc_v3
  save_dir: /home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/01_merfish_pfc_v4

preprocess:
  spatial_key: 'spatial'

model:
  hidden_dim: 512
  latent_dim: 64
  dropout_rate: 0.1
  gene_mask_ratio: 0.5
  cell_mask_ratio: 0.2
  n_encoder_layers: 3
  n_decoder_layers: 3
  niche_self_weight: 0.1   # z_niche = alpha * z_cell + (1-alpha) * neighbor；越大越保留细胞自身 identity

training:
  patch_size: 16384
  n_epochs: 20000
  learning_rate: 2e-3      
  warmup_epochs: 50
  patience: 100
  grad_accum_steps: 4
  use_amp: false
  infer_batch_size: 16384
  lambda_niche_recon: 1.0  # z_niche 对被遮盖基因的重建权重，偏空间上下文/niche
  lambda_cell_recon: 1.0   # z_cell 直接重建被遮盖基因的权重，提升 cell embedding 聚类/identity
  lambda_cell_mask: 1.0    # 遮盖整个细胞后由邻域恢复表达的权重，偏空间依赖学习
  lambda_binary: 0.1       # 二值表达/非表达重建任务权重，建议 0.1 ~ 0.3


logging:
  use_tensorboard: False
  tensorboard_save_dir: "./logs/tensorboard"
  use_wandb: true
  wandb_project: "StereoTrack"
  wandb_name: "01_Merfish_PFC_v4"
  wandb_save_dir: "/home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/01_merfish_pfc_v4/wandb"

# 01_Merfish_PFC