paths:
  data_path: /home/share/huadjyin/home/zhoutao3/tracks/example_data/03_han_mouse_brain/processed
  input_dir: /home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/03_han_mouse_processed_mae_v1
  save_dir: /home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/03_han_mouse_processed_mae_v1_train

preprocess:
  spatial_key: ccf
  coord_columns: [az, ay, ax]
  filter_gene_area: true
  min_gene_area: 0
  patch_axes: 2

model:
  hidden_dim: 512
  latent_dim: 64
  dropout_rate: 0.1
  gene_mask_ratio: 0.5
  cell_mask_ratio: 0.2
  n_encoder_layers: 3
  n_decoder_layers: 3
  niche_self_weight: 0.1

training:
  patch_size: 4096
  n_epochs: 100
  learning_rate: 2e-4
  warmup_epochs: 5
  patience: 20
  grad_accum_steps: 4
  use_amp: true
  infer_batch_size: 4096
  lambda_niche_recon: 1.0
  lambda_cell_recon: 1.0
  lambda_cell_mask: 1.0
  lambda_binary: 0.1

logging:
  use_tensorboard: false
  tensorboard_save_dir: ./logs/tensorboard
  use_wandb: true
  wandb_project: StereoTrack
  wandb_name: 03_han_mouse_processed_mae_v1
  wandb_save_dir: /home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/03_han_mouse_processed_mae_v1_train/wandb
