paths:
  data_path: /home/share/huadjyin/home/zhoutao3/tracks/example_data/07_macaque_brain/cortex
  save_dir: /home/share/huadjyin/home/zhoutao3/tracks/stereoTrack/out/07_macaque_brain_mae_v2

preprocess:
  spatial_key: 'ccf'

model:
  hidden_dim: 512
  latent_dim: 64
  dropout_rate: 0.1
  gene_mask_ratio: 0.5
  cell_mask_ratio: 0.2

training:
  patch_size: 8192
  n_epochs: 50
  learning_rate: 0.001
  patience: 20
  grad_accum_steps: 4
  use_amp: true
  infer_batch_size: 8192
